/// Country data with timezone offsets in minutes from UTC
/// Timezone data compiled from standard IANA timezone database
const Map<String, Map<String, dynamic>> countryData = {
  // North America
  'US': {'name': 'United States', 'offset': -300, 'timezone': 'America/New_York'},
  'CA': {'name': 'Canada', 'offset': -300, 'timezone': 'America/Toronto'},
  'MX': {'name': 'Mexico', 'offset': -360, 'timezone': 'America/Mexico_City'},

  // Central America & Caribbean
  'BS': {'name': 'Bahamas', 'offset': -300, 'timezone': 'America/Nassau'},
  'BB': {'name': 'Barbados', 'offset': -240, 'timezone': 'America/Barbados'},
  'AI': {'name': 'Anguilla', 'offset': -240, 'timezone': 'America/Anguilla'},
  'AG': {'name': 'Antigua and Barbuda', 'offset': -240, 'timezone': 'America/Antigua'},
  'VG': {'name': 'British Virgin Islands', 'offset': -240, 'timezone': 'America/Tortola'},
  'VI': {'name': 'U.S. Virgin Islands', 'offset': -240, 'timezone': 'America/St_Thomas'},
  'KY': {'name': 'Cayman Islands', 'offset': -300, 'timezone': 'America/Cayman'},
  'BM': {'name': 'Bermuda', 'offset': -240, 'timezone': 'Atlantic/Bermuda'},
  'GD': {'name': 'Grenada', 'offset': -240, 'timezone': 'America/Grenada'},
  'TC': {'name': 'Turks and Caicos', 'offset': -300, 'timezone': 'America/Grand_Turk'},
  'JM': {'name': 'Jamaica', 'offset': -300, 'timezone': 'America/Jamaica'},
  'MS': {'name': 'Montserrat', 'offset': -240, 'timezone': 'America/Montserrat'},
  'MP': {'name': 'Northern Mariana Islands', 'offset': 600, 'timezone': 'Pacific/Saipan'},
  'GU': {'name': 'Guam', 'offset': 600, 'timezone': 'Pacific/Guam'},
  'AS': {'name': 'American Samoa', 'offset': -660, 'timezone': 'Pacific/Pago_Pago'},
  'SX': {'name': 'Sint Maarten', 'offset': -240, 'timezone': 'America/Lower_Princes'},
  'LC': {'name': 'Saint Lucia', 'offset': -240, 'timezone': 'America/St_Lucia'},
  'DM': {'name': 'Dominica', 'offset': -240, 'timezone': 'America/Dominica'},
  'VC': {'name': 'Saint Vincent', 'offset': -240, 'timezone': 'America/St_Vincent'},
  'PR': {'name': 'Puerto Rico', 'offset': -240, 'timezone': 'America/Puerto_Rico'},
  'DO': {'name': 'Dominican Republic', 'offset': -240, 'timezone': 'America/Santo_Domingo'},
  'TT': {'name': 'Trinidad and Tobago', 'offset': -240, 'timezone': 'America/Port_of_Spain'},
  'KN': {'name': 'Saint Kitts and Nevis', 'offset': -240, 'timezone': 'America/St_Kitts'},
  'CU': {'name': 'Cuba', 'offset': -300, 'timezone': 'America/Havana'},
  'BZ': {'name': 'Belize', 'offset': -360, 'timezone': 'America/Belize'},
  'GT': {'name': 'Guatemala', 'offset': -360, 'timezone': 'America/Guatemala'},
  'SV': {'name': 'El Salvador', 'offset': -360, 'timezone': 'America/El_Salvador'},
  'HN': {'name': 'Honduras', 'offset': -360, 'timezone': 'America/Tegucigalpa'},
  'NI': {'name': 'Nicaragua', 'offset': -360, 'timezone': 'America/Managua'},
  'CR': {'name': 'Costa Rica', 'offset': -360, 'timezone': 'America/Costa_Rica'},
  'PA': {'name': 'Panama', 'offset': -300, 'timezone': 'America/Panama'},
  'PM': {'name': 'Saint Pierre', 'offset': -180, 'timezone': 'America/Miquelon'},
  'HT': {'name': 'Haiti', 'offset': -300, 'timezone': 'America/Port-au-Prince'},
  'GP': {'name': 'Guadeloupe', 'offset': -240, 'timezone': 'America/Guadeloupe'},

  // South America
  'BR': {'name': 'Brazil', 'offset': -180, 'timezone': 'America/Sao_Paulo'},
  'AR': {'name': 'Argentina', 'offset': -180, 'timezone': 'America/Argentina/Buenos_Aires'},
  'CL': {'name': 'Chile', 'offset': -240, 'timezone': 'America/Santiago'},
  'CO': {'name': 'Colombia', 'offset': -300, 'timezone': 'America/Bogota'},
  'PE': {'name': 'Peru', 'offset': -300, 'timezone': 'America/Lima'},
  'VE': {'name': 'Venezuela', 'offset': -240, 'timezone': 'America/Caracas'},
  'BO': {'name': 'Bolivia', 'offset': -240, 'timezone': 'America/La_Paz'},
  'GY': {'name': 'Guyana', 'offset': -240, 'timezone': 'America/Guyana'},
  'EC': {'name': 'Ecuador', 'offset': -300, 'timezone': 'America/Guayaquil'},
  'GF': {'name': 'French Guiana', 'offset': -180, 'timezone': 'America/Cayenne'},
  'PY': {'name': 'Paraguay', 'offset': -240, 'timezone': 'America/Asuncion'},
  'SR': {'name': 'Suriname', 'offset': -180, 'timezone': 'America/Paramaribo'},
  'UY': {'name': 'Uruguay', 'offset': -180, 'timezone': 'America/Montevideo'},
  'CW': {'name': 'Curacao', 'offset': -240, 'timezone': 'America/Curacao'},
  'FK': {'name': 'Falkland Islands', 'offset': -180, 'timezone': 'Atlantic/Stanley'},

  // Europe - Western
  'GB': {'name': 'United Kingdom', 'offset': 0, 'timezone': 'Europe/London'},
  'IE': {'name': 'Ireland', 'offset': 0, 'timezone': 'Europe/Dublin'},
  'PT': {'name': 'Portugal', 'offset': 0, 'timezone': 'Europe/Lisbon'},
  'IS': {'name': 'Iceland', 'offset': 0, 'timezone': 'Atlantic/Reykjavik'},

  // Europe - Central
  'FR': {'name': 'France', 'offset': 60, 'timezone': 'Europe/Paris'},
  'DE': {'name': 'Germany', 'offset': 60, 'timezone': 'Europe/Berlin'},
  'IT': {'name': 'Italy', 'offset': 60, 'timezone': 'Europe/Rome'},
  'ES': {'name': 'Spain', 'offset': 60, 'timezone': 'Europe/Madrid'},
  'NL': {'name': 'Netherlands', 'offset': 60, 'timezone': 'Europe/Amsterdam'},
  'BE': {'name': 'Belgium', 'offset': 60, 'timezone': 'Europe/Brussels'},
  'CH': {'name': 'Switzerland', 'offset': 60, 'timezone': 'Europe/Zurich'},
  'AT': {'name': 'Austria', 'offset': 60, 'timezone': 'Europe/Vienna'},
  'SE': {'name': 'Sweden', 'offset': 60, 'timezone': 'Europe/Stockholm'},
  'NO': {'name': 'Norway', 'offset': 60, 'timezone': 'Europe/Oslo'},
  'DK': {'name': 'Denmark', 'offset': 60, 'timezone': 'Europe/Copenhagen'},
  'PL': {'name': 'Poland', 'offset': 60, 'timezone': 'Europe/Warsaw'},
  'CZ': {'name': 'Czech Republic', 'offset': 60, 'timezone': 'Europe/Prague'},
  'SK': {'name': 'Slovakia', 'offset': 60, 'timezone': 'Europe/Bratislava'},
  'HU': {'name': 'Hungary', 'offset': 60, 'timezone': 'Europe/Budapest'},
  'HR': {'name': 'Croatia', 'offset': 60, 'timezone': 'Europe/Zagreb'},
  'SI': {'name': 'Slovenia', 'offset': 60, 'timezone': 'Europe/Ljubljana'},
  'LU': {'name': 'Luxembourg', 'offset': 60, 'timezone': 'Europe/Luxembourg'},
  'MC': {'name': 'Monaco', 'offset': 60, 'timezone': 'Europe/Monaco'},
  'AD': {'name': 'Andorra', 'offset': 60, 'timezone': 'Europe/Andorra'},
  'SM': {'name': 'San Marino', 'offset': 60, 'timezone': 'Europe/San_Marino'},
  'VA': {'name': 'Vatican', 'offset': 60, 'timezone': 'Europe/Vatican'},
  'LI': {'name': 'Liechtenstein', 'offset': 60, 'timezone': 'Europe/Vaduz'},
  'MT': {'name': 'Malta', 'offset': 60, 'timezone': 'Europe/Malta'},
  'GI': {'name': 'Gibraltar', 'offset': 60, 'timezone': 'Europe/Gibraltar'},
  'AL': {'name': 'Albania', 'offset': 60, 'timezone': 'Europe/Tirane'},
  'BA': {'name': 'Bosnia', 'offset': 60, 'timezone': 'Europe/Sarajevo'},
  'MK': {'name': 'North Macedonia', 'offset': 60, 'timezone': 'Europe/Skopje'},
  'ME': {'name': 'Montenegro', 'offset': 60, 'timezone': 'Europe/Podgorica'},
  'RS': {'name': 'Serbia', 'offset': 60, 'timezone': 'Europe/Belgrade'},
  'XK': {'name': 'Kosovo', 'offset': 60, 'timezone': 'Europe/Belgrade'},

  // Europe - Eastern
  'FI': {'name': 'Finland', 'offset': 120, 'timezone': 'Europe/Helsinki'},
  'GR': {'name': 'Greece', 'offset': 120, 'timezone': 'Europe/Athens'},
  'RO': {'name': 'Romania', 'offset': 120, 'timezone': 'Europe/Bucharest'},
  'BG': {'name': 'Bulgaria', 'offset': 120, 'timezone': 'Europe/Sofia'},
  'UA': {'name': 'Ukraine', 'offset': 120, 'timezone': 'Europe/Kiev'},
  'EE': {'name': 'Estonia', 'offset': 120, 'timezone': 'Europe/Tallinn'},
  'LV': {'name': 'Latvia', 'offset': 120, 'timezone': 'Europe/Riga'},
  'LT': {'name': 'Lithuania', 'offset': 120, 'timezone': 'Europe/Vilnius'},
  'MD': {'name': 'Moldova', 'offset': 120, 'timezone': 'Europe/Chisinau'},
  'CY': {'name': 'Cyprus', 'offset': 120, 'timezone': 'Asia/Nicosia'},

  // Europe - Eastern (UTC+3)
  'RU': {'name': 'Russia', 'offset': 180, 'timezone': 'Europe/Moscow'},
  'BY': {'name': 'Belarus', 'offset': 180, 'timezone': 'Europe/Minsk'},
  'TR': {'name': 'Turkey', 'offset': 180, 'timezone': 'Europe/Istanbul'},

  // Caucasus
  'AM': {'name': 'Armenia', 'offset': 240, 'timezone': 'Asia/Yerevan'},
  'AZ': {'name': 'Azerbaijan', 'offset': 240, 'timezone': 'Asia/Baku'},
  'GE': {'name': 'Georgia', 'offset': 240, 'timezone': 'Asia/Tbilisi'},

  // Middle East
  'AE': {'name': 'UAE', 'offset': 240, 'timezone': 'Asia/Dubai'},
  'SA': {'name': 'Saudi Arabia', 'offset': 180, 'timezone': 'Asia/Riyadh'},
  'IL': {'name': 'Israel', 'offset': 120, 'timezone': 'Asia/Jerusalem'},
  'LB': {'name': 'Lebanon', 'offset': 120, 'timezone': 'Asia/Beirut'},
  'JO': {'name': 'Jordan', 'offset': 120, 'timezone': 'Asia/Amman'},
  'IQ': {'name': 'Iraq', 'offset': 180, 'timezone': 'Asia/Baghdad'},
  'KW': {'name': 'Kuwait', 'offset': 180, 'timezone': 'Asia/Kuwait'},
  'QA': {'name': 'Qatar', 'offset': 180, 'timezone': 'Asia/Qatar'},
  'BH': {'name': 'Bahrain', 'offset': 180, 'timezone': 'Asia/Bahrain'},
  'OM': {'name': 'Oman', 'offset': 240, 'timezone': 'Asia/Muscat'},
  'EG': {'name': 'Egypt', 'offset': 120, 'timezone': 'Africa/Cairo'},
  'SY': {'name': 'Syria', 'offset': 120, 'timezone': 'Asia/Damascus'},
  'YE': {'name': 'Yemen', 'offset': 180, 'timezone': 'Asia/Aden'},
  'PS': {'name': 'Palestine', 'offset': 120, 'timezone': 'Asia/Gaza'},

  // Central Asia
  'KZ': {'name': 'Kazakhstan', 'offset': 360, 'timezone': 'Asia/Almaty'},
  'UZ': {'name': 'Uzbekistan', 'offset': 300, 'timezone': 'Asia/Tashkent'},
  'TJ': {'name': 'Tajikistan', 'offset': 300, 'timezone': 'Asia/Dushanbe'},
  'TM': {'name': 'Turkmenistan', 'offset': 300, 'timezone': 'Asia/Ashgabat'},
  'KG': {'name': 'Kyrgyzstan', 'offset': 360, 'timezone': 'Asia/Bishkek'},
  'AF': {'name': 'Afghanistan', 'offset': 270, 'timezone': 'Asia/Kabul'},

  // South Asia
  'IN': {'name': 'India', 'offset': 330, 'timezone': 'Asia/Kolkata'},
  'PK': {'name': 'Pakistan', 'offset': 300, 'timezone': 'Asia/Karachi'},
  'BD': {'name': 'Bangladesh', 'offset': 360, 'timezone': 'Asia/Dhaka'},
  'LK': {'name': 'Sri Lanka', 'offset': 330, 'timezone': 'Asia/Colombo'},
  'NP': {'name': 'Nepal', 'offset': 345, 'timezone': 'Asia/Kathmandu'},
  'BT': {'name': 'Bhutan', 'offset': 360, 'timezone': 'Asia/Thimphu'},
  'MV': {'name': 'Maldives', 'offset': 300, 'timezone': 'Indian/Maldives'},
  'IR': {'name': 'Iran', 'offset': 210, 'timezone': 'Asia/Tehran'},

  // Southeast Asia
  'ID': {'name': 'Indonesia', 'offset': 420, 'timezone': 'Asia/Jakarta'},
  'TH': {'name': 'Thailand', 'offset': 420, 'timezone': 'Asia/Bangkok'},
  'MY': {'name': 'Malaysia', 'offset': 480, 'timezone': 'Asia/Kuala_Lumpur'},
  'PH': {'name': 'Philippines', 'offset': 480, 'timezone': 'Asia/Manila'},
  'VN': {'name': 'Vietnam', 'offset': 420, 'timezone': 'Asia/Ho_Chi_Minh'},
  'MM': {'name': 'Myanmar', 'offset': 390, 'timezone': 'Asia/Yangon'},
  'KH': {'name': 'Cambodia', 'offset': 420, 'timezone': 'Asia/Phnom_Penh'},
  'LA': {'name': 'Laos', 'offset': 420, 'timezone': 'Asia/Vientiane'},
  'SG': {'name': 'Singapore', 'offset': 480, 'timezone': 'Asia/Singapore'},
  'BN': {'name': 'Brunei', 'offset': 480, 'timezone': 'Asia/Brunei'},
  'TL': {'name': 'East Timor', 'offset': 540, 'timezone': 'Asia/Dili'},

  // East Asia
  'CN': {'name': 'China', 'offset': 480, 'timezone': 'Asia/Shanghai'},
  'JP': {'name': 'Japan', 'offset': 540, 'timezone': 'Asia/Tokyo'},
  'KR': {'name': 'South Korea', 'offset': 540, 'timezone': 'Asia/Seoul'},
  'KP': {'name': 'North Korea', 'offset': 540, 'timezone': 'Asia/Pyongyang'},
  'HK': {'name': 'Hong Kong', 'offset': 480, 'timezone': 'Asia/Hong_Kong'},
  'MO': {'name': 'Macau', 'offset': 480, 'timezone': 'Asia/Macau'},
  'TW': {'name': 'Taiwan', 'offset': 480, 'timezone': 'Asia/Taipei'},
  'MN': {'name': 'Mongolia', 'offset': 480, 'timezone': 'Asia/Ulaanbaatar'},

  // Oceania
  'AU': {'name': 'Australia', 'offset': 660, 'timezone': 'Australia/Sydney'},
  'NZ': {'name': 'New Zealand', 'offset': 780, 'timezone': 'Pacific/Auckland'},
  'FJ': {'name': 'Fiji', 'offset': 720, 'timezone': 'Pacific/Fiji'},
  'PG': {'name': 'Papua New Guinea', 'offset': 600, 'timezone': 'Pacific/Port_Moresby'},
  'NC': {'name': 'New Caledonia', 'offset': 660, 'timezone': 'Pacific/Noumea'},
  'SB': {'name': 'Solomon Islands', 'offset': 660, 'timezone': 'Pacific/Guadalcanal'},
  'VU': {'name': 'Vanuatu', 'offset': 660, 'timezone': 'Pacific/Efate'},
  'PF': {'name': 'French Polynesia', 'offset': -600, 'timezone': 'Pacific/Tahiti'},
  'WS': {'name': 'Samoa', 'offset': 780, 'timezone': 'Pacific/Apia'},
  'TO': {'name': 'Tonga', 'offset': 780, 'timezone': 'Pacific/Tongatapu'},
  'CK': {'name': 'Cook Islands', 'offset': -600, 'timezone': 'Pacific/Rarotonga'},
  'PW': {'name': 'Palau', 'offset': 540, 'timezone': 'Pacific/Palau'},
  'FM': {'name': 'Micronesia', 'offset': 660, 'timezone': 'Pacific/Pohnpei'},
  'MH': {'name': 'Marshall Islands', 'offset': 720, 'timezone': 'Pacific/Majuro'},
  'KI': {'name': 'Kiribati', 'offset': 720, 'timezone': 'Pacific/Tarawa'},
  'NR': {'name': 'Nauru', 'offset': 720, 'timezone': 'Pacific/Nauru'},
  'TV': {'name': 'Tuvalu', 'offset': 720, 'timezone': 'Pacific/Funafuti'},
  'WF': {'name': 'Wallis and Futuna', 'offset': 720, 'timezone': 'Pacific/Wallis'},
  'TK': {'name': 'Tokelau', 'offset': 780, 'timezone': 'Pacific/Fakaofo'},
  'NU': {'name': 'Niue', 'offset': -660, 'timezone': 'Pacific/Niue'},
  'AQ': {'name': 'Antarctica', 'offset': 720, 'timezone': 'Antarctica/McMurdo'},

  // Africa - North
  'MA': {'name': 'Morocco', 'offset': 60, 'timezone': 'Africa/Casablanca'},
  'DZ': {'name': 'Algeria', 'offset': 60, 'timezone': 'Africa/Algiers'},
  'TN': {'name': 'Tunisia', 'offset': 60, 'timezone': 'Africa/Tunis'},
  'LY': {'name': 'Libya', 'offset': 120, 'timezone': 'Africa/Tripoli'},
  'SD': {'name': 'Sudan', 'offset': 120, 'timezone': 'Africa/Khartoum'},
  'SS': {'name': 'South Sudan', 'offset': 120, 'timezone': 'Africa/Juba'},

  // Africa - West
  'NG': {'name': 'Nigeria', 'offset': 60, 'timezone': 'Africa/Lagos'},
  'GH': {'name': 'Ghana', 'offset': 0, 'timezone': 'Africa/Accra'},
  'SN': {'name': 'Senegal', 'offset': 0, 'timezone': 'Africa/Dakar'},
  'CI': {'name': 'Ivory Coast', 'offset': 0, 'timezone': 'Africa/Abidjan'},
  'CM': {'name': 'Cameroon', 'offset': 60, 'timezone': 'Africa/Douala'},
  'BF': {'name': 'Burkina Faso', 'offset': 0, 'timezone': 'Africa/Ouagadougou'},
  'ML': {'name': 'Mali', 'offset': 0, 'timezone': 'Africa/Bamako'},
  'NE': {'name': 'Niger', 'offset': 60, 'timezone': 'Africa/Niamey'},
  'TG': {'name': 'Togo', 'offset': 0, 'timezone': 'Africa/Lome'},
  'BJ': {'name': 'Benin', 'offset': 60, 'timezone': 'Africa/Porto-Novo'},
  'GN': {'name': 'Guinea', 'offset': 0, 'timezone': 'Africa/Conakry'},
  'SL': {'name': 'Sierra Leone', 'offset': 0, 'timezone': 'Africa/Freetown'},
  'LR': {'name': 'Liberia', 'offset': 0, 'timezone': 'Africa/Monrovia'},
  'MR': {'name': 'Mauritania', 'offset': 0, 'timezone': 'Africa/Nouakchott'},
  'GM': {'name': 'Gambia', 'offset': 0, 'timezone': 'Africa/Banjul'},
  'GW': {'name': 'Guinea-Bissau', 'offset': 0, 'timezone': 'Africa/Bissau'},
  'CV': {'name': 'Cape Verde', 'offset': -60, 'timezone': 'Atlantic/Cape_Verde'},
  'ST': {'name': 'Sao Tome', 'offset': 0, 'timezone': 'Africa/Sao_Tome'},
  'GQ': {'name': 'Equatorial Guinea', 'offset': 60, 'timezone': 'Africa/Malabo'},
  'GA': {'name': 'Gabon', 'offset': 60, 'timezone': 'Africa/Libreville'},
  'CG': {'name': 'Congo', 'offset': 60, 'timezone': 'Africa/Brazzaville'},
  'CD': {'name': 'DR Congo', 'offset': 60, 'timezone': 'Africa/Kinshasa'},
  'AO': {'name': 'Angola', 'offset': 60, 'timezone': 'Africa/Luanda'},
  'TD': {'name': 'Chad', 'offset': 60, 'timezone': 'Africa/Ndjamena'},
  'CF': {'name': 'Central African Republic', 'offset': 60, 'timezone': 'Africa/Bangui'},

  // Africa - East
  'KE': {'name': 'Kenya', 'offset': 180, 'timezone': 'Africa/Nairobi'},
  'TZ': {'name': 'Tanzania', 'offset': 180, 'timezone': 'Africa/Dar_es_Salaam'},
  'UG': {'name': 'Uganda', 'offset': 180, 'timezone': 'Africa/Kampala'},
  'ET': {'name': 'Ethiopia', 'offset': 180, 'timezone': 'Africa/Addis_Ababa'},
  'SO': {'name': 'Somalia', 'offset': 180, 'timezone': 'Africa/Mogadishu'},
  'DJ': {'name': 'Djibouti', 'offset': 180, 'timezone': 'Africa/Djibouti'},
  'ER': {'name': 'Eritrea', 'offset': 180, 'timezone': 'Africa/Asmara'},
  'RW': {'name': 'Rwanda', 'offset': 120, 'timezone': 'Africa/Kigali'},
  'BI': {'name': 'Burundi', 'offset': 120, 'timezone': 'Africa/Bujumbura'},
  'KM': {'name': 'Comoros', 'offset': 180, 'timezone': 'Indian/Comoro'},
  'SC': {'name': 'Seychelles', 'offset': 240, 'timezone': 'Indian/Mahe'},
  'MU': {'name': 'Mauritius', 'offset': 240, 'timezone': 'Indian/Mauritius'},
  'RE': {'name': 'Reunion', 'offset': 240, 'timezone': 'Indian/Reunion'},
  'MG': {'name': 'Madagascar', 'offset': 180, 'timezone': 'Indian/Antananarivo'},

  // Africa - Southern
  'ZA': {'name': 'South Africa', 'offset': 120, 'timezone': 'Africa/Johannesburg'},
  'NA': {'name': 'Namibia', 'offset': 120, 'timezone': 'Africa/Windhoek'},
  'BW': {'name': 'Botswana', 'offset': 120, 'timezone': 'Africa/Gaborone'},
  'ZW': {'name': 'Zimbabwe', 'offset': 120, 'timezone': 'Africa/Harare'},
  'ZM': {'name': 'Zambia', 'offset': 120, 'timezone': 'Africa/Lusaka'},
  'MW': {'name': 'Malawi', 'offset': 120, 'timezone': 'Africa/Blantyre'},
  'MZ': {'name': 'Mozambique', 'offset': 120, 'timezone': 'Africa/Maputo'},
  'LS': {'name': 'Lesotho', 'offset': 120, 'timezone': 'Africa/Maseru'},
  'SZ': {'name': 'Eswatini', 'offset': 120, 'timezone': 'Africa/Mbabane'},

  // Special territories
  'IO': {'name': 'British Indian Ocean', 'offset': 360, 'timezone': 'Indian/Chagos'},
};
