/// Country data with timezone offsets in minutes from UTC
const Map<String, Map<String, dynamic>> countryData = {
  'IN': {'name': 'India', 'offset': 330, 'timezone': 'Asia/Kolkata'},
  'US': {'name': 'United States', 'offset': -300, 'timezone': 'America/New_York'},
  'GB': {'name': 'United Kingdom', 'offset': 0, 'timezone': 'Europe/London'},
  'AU': {'name': 'Australia', 'offset': 660, 'timezone': 'Australia/Sydney'},
  'JP': {'name': 'Japan', 'offset': 540, 'timezone': 'Asia/Tokyo'},
  'CN': {'name': 'China', 'offset': 480, 'timezone': 'Asia/Shanghai'},
  'DE': {'name': 'Germany', 'offset': 60, 'timezone': 'Europe/Berlin'},
  'FR': {'name': 'France', 'offset': 60, 'timezone': 'Europe/Paris'},
  'BR': {'name': 'Brazil', 'offset': -180, 'timezone': 'America/Sao_Paulo'},
  'ZA': {'name': 'South Africa', 'offset': 120, 'timezone': 'Africa/Johannesburg'},
  'AE': {'name': 'UAE', 'offset': 240, 'timezone': 'Asia/Dubai'},
  'SG': {'name': 'Singapore', 'offset': 480, 'timezone': 'Asia/Singapore'},
  'CA': {'name': 'Canada', 'offset': -300, 'timezone': 'America/Toronto'},
  'MX': {'name': 'Mexico', 'offset': -360, 'timezone': 'America/Mexico_City'},
  'IT': {'name': 'Italy', 'offset': 60, 'timezone': 'Europe/Rome'},
  'ES': {'name': 'Spain', 'offset': 60, 'timezone': 'Europe/Madrid'},
  'RU': {'name': 'Russia', 'offset': 180, 'timezone': 'Europe/Moscow'},
  'KR': {'name': 'South Korea', 'offset': 540, 'timezone': 'Asia/Seoul'},
  'ID': {'name': 'Indonesia', 'offset': 420, 'timezone': 'Asia/Jakarta'},
  'TH': {'name': 'Thailand', 'offset': 420, 'timezone': 'Asia/Bangkok'},
  'MY': {'name': 'Malaysia', 'offset': 480, 'timezone': 'Asia/Kuala_Lumpur'},
  'PH': {'name': 'Philippines', 'offset': 480, 'timezone': 'Asia/Manila'},
  'VN': {'name': 'Vietnam', 'offset': 420, 'timezone': 'Asia/Ho_Chi_Minh'},
  'PK': {'name': 'Pakistan', 'offset': 300, 'timezone': 'Asia/Karachi'},
  'BD': {'name': 'Bangladesh', 'offset': 360, 'timezone': 'Asia/Dhaka'},
  'NZ': {'name': 'New Zealand', 'offset': 780, 'timezone': 'Pacific/Auckland'},
};
