/// Country data with timezone offsets in minutes from UTC
const Map<String, Map<String, dynamic>> countryData = {
  // North America
  'US': {'name': 'United States', 'offset': -300, 'timezone': 'America/New_York'},
  'CA': {'name': 'Canada', 'offset': -300, 'timezone': 'America/Toronto'},
  'MX': {'name': 'Mexico', 'offset': -360, 'timezone': 'America/Mexico_City'},

  // South America
  'BR': {'name': 'Brazil', 'offset': -180, 'timezone': 'America/Sao_Paulo'},
  'AR': {'name': 'Argentina', 'offset': -180, 'timezone': 'America/Argentina/Buenos_Aires'},
  'CL': {'name': 'Chile', 'offset': -240, 'timezone': 'America/Santiago'},
  'CO': {'name': 'Colombia', 'offset': -300, 'timezone': 'America/Bogota'},
  'PE': {'name': 'Peru', 'offset': -300, 'timezone': 'America/Lima'},
  'VE': {'name': 'Venezuela', 'offset': -240, 'timezone': 'America/Caracas'},

  // Europe
  'GB': {'name': 'United Kingdom', 'offset': 0, 'timezone': 'Europe/London'},
  'FR': {'name': 'France', 'offset': 60, 'timezone': 'Europe/Paris'},
  'DE': {'name': 'Germany', 'offset': 60, 'timezone': 'Europe/Berlin'},
  'IT': {'name': 'Italy', 'offset': 60, 'timezone': 'Europe/Rome'},
  'ES': {'name': 'Spain', 'offset': 60, 'timezone': 'Europe/Madrid'},
  'NL': {'name': 'Netherlands', 'offset': 60, 'timezone': 'Europe/Amsterdam'},
  'BE': {'name': 'Belgium', 'offset': 60, 'timezone': 'Europe/Brussels'},
  'CH': {'name': 'Switzerland', 'offset': 60, 'timezone': 'Europe/Zurich'},
  'AT': {'name': 'Austria', 'offset': 60, 'timezone': 'Europe/Vienna'},
  'SE': {'name': 'Sweden', 'offset': 60, 'timezone': 'Europe/Stockholm'},
  'NO': {'name': 'Norway', 'offset': 60, 'timezone': 'Europe/Oslo'},
  'DK': {'name': 'Denmark', 'offset': 60, 'timezone': 'Europe/Copenhagen'},
  'FI': {'name': 'Finland', 'offset': 120, 'timezone': 'Europe/Helsinki'},
  'PL': {'name': 'Poland', 'offset': 60, 'timezone': 'Europe/Warsaw'},
  'GR': {'name': 'Greece', 'offset': 120, 'timezone': 'Europe/Athens'},
  'PT': {'name': 'Portugal', 'offset': 0, 'timezone': 'Europe/Lisbon'},
  'IE': {'name': 'Ireland', 'offset': 0, 'timezone': 'Europe/Dublin'},
  'RU': {'name': 'Russia', 'offset': 180, 'timezone': 'Europe/Moscow'},
  'UA': {'name': 'Ukraine', 'offset': 120, 'timezone': 'Europe/Kiev'},
  'CZ': {'name': 'Czech Republic', 'offset': 60, 'timezone': 'Europe/Prague'},
  'RO': {'name': 'Romania', 'offset': 120, 'timezone': 'Europe/Bucharest'},

  // Middle East
  'AE': {'name': 'UAE', 'offset': 240, 'timezone': 'Asia/Dubai'},
  'SA': {'name': 'Saudi Arabia', 'offset': 180, 'timezone': 'Asia/Riyadh'},
  'IL': {'name': 'Israel', 'offset': 120, 'timezone': 'Asia/Jerusalem'},
  'TR': {'name': 'Turkey', 'offset': 180, 'timezone': 'Europe/Istanbul'},
  'LB': {'name': 'Lebanon', 'offset': 120, 'timezone': 'Asia/Beirut'},
  'JO': {'name': 'Jordan', 'offset': 120, 'timezone': 'Asia/Amman'},
  'IQ': {'name': 'Iraq', 'offset': 180, 'timezone': 'Asia/Baghdad'},
  'KW': {'name': 'Kuwait', 'offset': 180, 'timezone': 'Asia/Kuwait'},
  'QA': {'name': 'Qatar', 'offset': 180, 'timezone': 'Asia/Qatar'},
  'BH': {'name': 'Bahrain', 'offset': 180, 'timezone': 'Asia/Bahrain'},
  'OM': {'name': 'Oman', 'offset': 240, 'timezone': 'Asia/Muscat'},
  'EG': {'name': 'Egypt', 'offset': 120, 'timezone': 'Africa/Cairo'},

  // Asia
  'IN': {'name': 'India', 'offset': 330, 'timezone': 'Asia/Kolkata'},
  'CN': {'name': 'China', 'offset': 480, 'timezone': 'Asia/Shanghai'},
  'JP': {'name': 'Japan', 'offset': 540, 'timezone': 'Asia/Tokyo'},
  'KR': {'name': 'South Korea', 'offset': 540, 'timezone': 'Asia/Seoul'},
  'SG': {'name': 'Singapore', 'offset': 480, 'timezone': 'Asia/Singapore'},
  'HK': {'name': 'Hong Kong', 'offset': 480, 'timezone': 'Asia/Hong_Kong'},
  'TW': {'name': 'Taiwan', 'offset': 480, 'timezone': 'Asia/Taipei'},
  'PK': {'name': 'Pakistan', 'offset': 300, 'timezone': 'Asia/Karachi'},
  'BD': {'name': 'Bangladesh', 'offset': 360, 'timezone': 'Asia/Dhaka'},
  'ID': {'name': 'Indonesia', 'offset': 420, 'timezone': 'Asia/Jakarta'},
  'TH': {'name': 'Thailand', 'offset': 420, 'timezone': 'Asia/Bangkok'},
  'MY': {'name': 'Malaysia', 'offset': 480, 'timezone': 'Asia/Kuala_Lumpur'},
  'PH': {'name': 'Philippines', 'offset': 480, 'timezone': 'Asia/Manila'},
  'VN': {'name': 'Vietnam', 'offset': 420, 'timezone': 'Asia/Ho_Chi_Minh'},
  'LK': {'name': 'Sri Lanka', 'offset': 330, 'timezone': 'Asia/Colombo'},
  'NP': {'name': 'Nepal', 'offset': 345, 'timezone': 'Asia/Kathmandu'},
  'MM': {'name': 'Myanmar', 'offset': 390, 'timezone': 'Asia/Yangon'},
  'KH': {'name': 'Cambodia', 'offset': 420, 'timezone': 'Asia/Phnom_Penh'},
  'LA': {'name': 'Laos', 'offset': 420, 'timezone': 'Asia/Vientiane'},
  'MN': {'name': 'Mongolia', 'offset': 480, 'timezone': 'Asia/Ulaanbaatar'},
  'KZ': {'name': 'Kazakhstan', 'offset': 360, 'timezone': 'Asia/Almaty'},
  'UZ': {'name': 'Uzbekistan', 'offset': 300, 'timezone': 'Asia/Tashkent'},
  'AF': {'name': 'Afghanistan', 'offset': 270, 'timezone': 'Asia/Kabul'},
  'IR': {'name': 'Iran', 'offset': 210, 'timezone': 'Asia/Tehran'},

  // Oceania
  'AU': {'name': 'Australia', 'offset': 660, 'timezone': 'Australia/Sydney'},
  'NZ': {'name': 'New Zealand', 'offset': 780, 'timezone': 'Pacific/Auckland'},
  'FJ': {'name': 'Fiji', 'offset': 720, 'timezone': 'Pacific/Fiji'},

  // Africa
  'ZA': {'name': 'South Africa', 'offset': 120, 'timezone': 'Africa/Johannesburg'},
  'NG': {'name': 'Nigeria', 'offset': 60, 'timezone': 'Africa/Lagos'},
  'KE': {'name': 'Kenya', 'offset': 180, 'timezone': 'Africa/Nairobi'},
  'GH': {'name': 'Ghana', 'offset': 0, 'timezone': 'Africa/Accra'},
  'ET': {'name': 'Ethiopia', 'offset': 180, 'timezone': 'Africa/Addis_Ababa'},
  'TZ': {'name': 'Tanzania', 'offset': 180, 'timezone': 'Africa/Dar_es_Salaam'},
  'UG': {'name': 'Uganda', 'offset': 180, 'timezone': 'Africa/Kampala'},
  'DZ': {'name': 'Algeria', 'offset': 60, 'timezone': 'Africa/Algiers'},
  'MA': {'name': 'Morocco', 'offset': 60, 'timezone': 'Africa/Casablanca'},
  'TN': {'name': 'Tunisia', 'offset': 60, 'timezone': 'Africa/Tunis'},
  'ZW': {'name': 'Zimbabwe', 'offset': 120, 'timezone': 'Africa/Harare'},
};
